// src/lib/sound.ts
//
// A tiny Web Audio engine for the portfolio's UI sound layer. It is a module
// singleton (like lib/scroll.ts) so it survives StrictMode's double effect
// invocation and can be reached from anywhere without a React context.
//
// Design goals, matching the rest of the site's restraint:
//   • Preloaded, decoded buffers → zero-latency playback.
//   • Respects autoplay policy — the AudioContext is created suspended and only
//     resumed on a real user gesture (pointerdown / keydown / touchstart).
//   • Never annoying: every one-shot is throttled, and a small priority "duck"
//     keeps a lesser sound (a hover tick) from stepping on a more important one
//     (a success chime), so sounds don't pile up.
//   • Global mute, persisted to localStorage, defaulting to muted when the user
//     prefers reduced motion (the same restraint the visuals honor).
//
// The sound files are generated by scripts/generate-sounds.mjs. They are
// imported (not referenced by absolute path) so Vite fingerprints them and
// resolves the deploy base path — absolute "/sounds/x.wav" URLs would 404 under
// the project's /Pranav-Parmar-portfolio/ base.

import popUrl from "../assets/sounds/pop.wav";
import tickUrl from "../assets/sounds/tick.wav";
import whooshUrl from "../assets/sounds/whoosh.wav";
import cardhoverUrl from "../assets/sounds/cardhover.wav";
import transitionUrl from "../assets/sounds/transition.wav";
import dragUrl from "../assets/sounds/drag.wav";
import startupUrl from "../assets/sounds/startup.wav";
import bloomUrl from "../assets/sounds/bloom.wav";
import chimeUrl from "../assets/sounds/chime.wav";

export type SoundName =
  | "pop"
  | "tick"
  | "whoosh"
  | "cardhover"
  | "transition"
  | "drag"
  | "startup"
  | "bloom"
  | "chime";

type SoundSpec = {
  url: string;
  /** Per-sound mix level (buffers are peak-normalized in the generator). */
  gain: number;
  /** Minimum ms between triggers of this sound — throttle + anti-overlap. */
  throttle: number;
  /** Higher wins: a lower-priority sound is muted while a higher one rings. */
  priority: number;
  /**
   * Max ± playback-rate jitter applied per trigger (0.06 = ±6%), so repeats
   * never sound like the same flat sample. Kept small/zero for the musical
   * one-shots so their pitch stays intentional.
   */
  pitch: number;
};

// Effective loudness ≈ MASTER_GAIN × gain, kept within the site's subtle
// 15–35% band (the welcome sits a touch louder as a one-time moment).
const SPECS: Record<SoundName, SoundSpec> = {
  tick: { url: tickUrl, gain: 0.14, throttle: 55, priority: 0, pitch: 0.08 },
  cardhover: { url: cardhoverUrl, gain: 0.16, throttle: 90, priority: 0, pitch: 0.05 },
  whoosh: { url: whooshUrl, gain: 0.18, throttle: 900, priority: 1, pitch: 0.05 },
  pop: { url: popUrl, gain: 0.3, throttle: 80, priority: 2, pitch: 0.06 },
  transition: { url: transitionUrl, gain: 0.18, throttle: 500, priority: 3, pitch: 0.03 },
  chime: { url: chimeUrl, gain: 0.3, throttle: 200, priority: 4, pitch: 0.03 },
  bloom: { url: bloomUrl, gain: 0.3, throttle: 400, priority: 5, pitch: 0.02 },
  startup: { url: startupUrl, gain: 0.42, throttle: 1000, priority: 6, pitch: 0 },
  // `drag` is a sustained loop managed separately, so it needs no throttle
  // and stays out of the one-shot priority ducking.
  drag: { url: dragUrl, gain: 0.15, throttle: 0, priority: 0, pitch: 0 },
};

const MASTER_GAIN = 0.85;
const STORAGE_KEY = "soundMuted";
const DRAG_FADE_IN = 0.12; // s
const DRAG_FADE_OUT = 0.22; // s

/* --------------------------------- state ---------------------------------- */

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
const buffers = new Map<SoundName, AudioBuffer>();
const lastPlayed = new Map<SoundName, number>(); // performance.now() timestamps

// One-shot ducking window, expressed in AudioContext time (seconds).
let duckUntil = 0;
let duckPriority = -1;

// Sustained drag loop. `dragWanted` guards the async-resume race: if the drag
// ends before a suspended context finishes resuming, the deferred start bails
// instead of leaving an orphaned loop ringing forever.
let dragSource: AudioBufferSourceNode | null = null;
let dragGain: GainNode | null = null;
let dragWanted = false;

let muted = readInitialMuted();
let initialized = false;
const muteListeners = new Set<(m: boolean) => void>();

/* --------------------------------- helpers -------------------------------- */

function now(): number {
  // performance.now() is monotonic and always available in the browser.
  return typeof performance !== "undefined" ? performance.now() : 0;
}

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    !!window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches
  );
}

function readInitialMuted(): boolean {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "1") return true;
    if (stored === "0") return false;
  } catch {
    /* ignore storage errors (private mode, etc.) */
  }
  // No stored preference: stay silent by default for reduced-motion users,
  // audible for everyone else.
  return prefersReducedMotion();
}

function getCtx(): AudioContext | null {
  if (ctx) return ctx;
  if (typeof window === "undefined") return null;
  const Ctor =
    window.AudioContext ||
    (window as unknown as { webkitAudioContext?: typeof AudioContext })
      .webkitAudioContext;
  if (!Ctor) return null; // Web Audio unsupported → the whole layer no-ops
  try {
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = MASTER_GAIN;
    master.connect(ctx.destination);
  } catch {
    ctx = null;
    master = null;
  }
  return ctx;
}

/** Resume the context — only effective inside a user-gesture call stack. */
function resume(): void {
  const c = getCtx();
  if (c && c.state !== "running") c.resume().catch(() => {});
}

/* --------------------------------- public --------------------------------- */

/**
 * Create the AudioContext (suspended) and decode every buffer once. Safe to
 * call repeatedly — subsequent calls are ignored. Kick this off from an idle
 * callback so it never competes with first paint.
 */
export function initSound(): void {
  if (initialized) return;
  initialized = true;
  const c = getCtx();
  if (!c) return;

  (Object.keys(SPECS) as SoundName[]).forEach(async (name) => {
    try {
      const res = await fetch(SPECS[name].url);
      const arr = await res.arrayBuffer();
      const buf = await c.decodeAudioData(arr);
      buffers.set(name, buf);
    } catch {
      /* a missing/undecodable sound simply never plays */
    }
  });
}

/** Wire up the one-shot gesture listeners that unlock audio. Idempotent. */
export function unlockOnGesture(): () => void {
  if (typeof window === "undefined") return () => {};
  const unlock = () => resume();
  const opts: AddEventListenerOptions = { passive: true, capture: true };
  window.addEventListener("pointerdown", unlock, opts);
  window.addEventListener("keydown", unlock, opts);
  window.addEventListener("touchstart", unlock, opts);
  return () => {
    window.removeEventListener("pointerdown", unlock, opts);
    window.removeEventListener("keydown", unlock, opts);
    window.removeEventListener("touchstart", unlock, opts);
  };
}

function fire(name: SoundName, intensity = 1): void {
  const c = ctx;
  const spec = SPECS[name];
  const buf = buffers.get(name);
  if (!c || !master || !buf || c.state !== "running") return;

  // Throttle repeats of the same sound.
  const t = now();
  const last = lastPlayed.get(name);
  if (last !== undefined && t - last < spec.throttle) return;

  // Priority duck: while a more important one-shot is ringing, drop this one.
  const at = c.currentTime;
  if (at < duckUntil && spec.priority < duckPriority) return;

  lastPlayed.set(name, t);
  if (spec.priority >= duckPriority || at >= duckUntil) {
    duckPriority = spec.priority;
    duckUntil = at + buf.duration;
  }

  const src = c.createBufferSource();
  src.buffer = buf;
  // Slight pitch variation each trigger so repeats feel organic, nudged up a
  // touch by intensity (used for scroll-speed reactivity).
  const jitter = 1 + (Math.random() * 2 - 1) * spec.pitch;
  src.playbackRate.value = jitter + (intensity - 1) * 0.06;
  const g = c.createGain();
  g.gain.value = spec.gain * Math.max(0.15, Math.min(1.3, intensity));
  src.connect(g).connect(master);
  src.onended = () => {
    src.disconnect();
    g.disconnect();
  };
  src.start();
}

/**
 * Play a one-shot sound. `gesture` must be true when the call originates from a
 * real user gesture (a click, the intro dismiss): the context is resumed and
 * the sound is played the moment it is running. Non-gesture callers (scroll,
 * hover, viewport observers) only make sound once the context is already
 * unlocked — this prevents queued sounds from firing late on the first click.
 *
 * `intensity` (default 1) scales the mix level and nudges pitch — the scroll
 * handler passes scroll speed through it so a fast flick sounds airier than a
 * gentle nudge.
 */
export function playSound(name: SoundName, gesture = false, intensity = 1): void {
  if (muted) return;
  const c = getCtx();
  if (!c || !buffers.has(name)) return;

  if (c.state === "running") {
    fire(name, intensity);
  } else if (gesture) {
    c.resume()
      .then(() => fire(name, intensity))
      .catch(() => {});
  }
  // else: not running and not a gesture → stay silent (no queueing).
}

/** Begin the sustained drag glide, fading in from silence. Idempotent. */
export function startDrag(): void {
  if (muted || dragSource) return;
  const c = getCtx();
  const buf = buffers.get("drag");
  if (!c || !master || !buf) return;
  const bus = master; // const alias so the nested closure keeps the narrowing
  dragWanted = true;

  const start = () => {
    // Bail if the drag already ended while the context was still resuming.
    if (!dragWanted || dragSource || c.state !== "running") return;
    const src = c.createBufferSource();
    src.buffer = buf;
    src.loop = true;
    const g = c.createGain();
    const at = c.currentTime;
    g.gain.setValueAtTime(0.0001, at);
    g.gain.linearRampToValueAtTime(SPECS.drag.gain, at + DRAG_FADE_IN);
    src.connect(g).connect(bus);
    src.start();
    dragSource = src;
    dragGain = g;
  };

  if (c.state === "running") start();
  else c.resume().then(start).catch(() => {});
}

/** Fade the drag glide out and stop it. Safe to call when nothing is playing. */
export function stopDrag(): void {
  dragWanted = false; // cancel any pending deferred start (see startDrag)
  const c = ctx;
  const src = dragSource;
  const g = dragGain;
  dragSource = null;
  dragGain = null;
  if (!c || !src || !g) return;
  const at = c.currentTime;
  try {
    g.gain.cancelScheduledValues(at);
    g.gain.setValueAtTime(g.gain.value, at);
    g.gain.linearRampToValueAtTime(0.0001, at + DRAG_FADE_OUT);
    src.stop(at + DRAG_FADE_OUT + 0.02);
  } catch {
    /* already stopped */
  }
}

export function isMuted(): boolean {
  return muted;
}

export function setMuted(value: boolean): void {
  if (value === muted) return;
  muted = value;
  try {
    localStorage.setItem(STORAGE_KEY, value ? "1" : "0");
  } catch {
    /* ignore storage errors */
  }
  if (muted) stopDrag(); // never leave a loop ringing after a mute
  muteListeners.forEach((cb) => cb(muted));
}

export function toggleMuted(): boolean {
  setMuted(!muted);
  return muted;
}

/** Subscribe to mute changes; returns an unsubscribe fn. */
export function subscribeMuted(cb: (m: boolean) => void): () => void {
  muteListeners.add(cb);
  return () => muteListeners.delete(cb);
}
