// src/platform/audio/engine/catalog.ts
//
// The cue catalogue: what each sound is, how loud it sits in the mix, how often
// it may retrigger and how it ranks against the others. Nothing here is
// stateful, so this module is a leaf — every other engine file may import it.
//
// The WAV files are generated by scripts/generate-sounds.mjs. They are imported
// (not referenced by absolute path) so Vite fingerprints them and resolves the
// deploy base path — absolute "/cues/x.wav" URLs would 404 under the project's
// /Pranav-Parmar-portfolio/ base.

import bloomUrl from "@assets/audio/cues/bloom.wav";
import cardhoverUrl from "@assets/audio/cues/cardhover.wav";
import chimeUrl from "@assets/audio/cues/chime.wav";
import dragUrl from "@assets/audio/cues/drag.wav";
import popUrl from "@assets/audio/cues/pop.wav";
import startupUrl from "@assets/audio/cues/startup.wav";
import tickUrl from "@assets/audio/cues/tick.wav";
import transitionUrl from "@assets/audio/cues/transition.wav";
import whooshUrl from "@assets/audio/cues/whoosh.wav";

export type CueName =
  | "pop"
  | "tick"
  | "whoosh"
  | "cardhover"
  | "transition"
  | "drag"
  | "startup"
  | "bloom"
  | "chime";

export type CueSpec = {
  url: string;
  /** Per-cue mix level (buffers are peak-normalized in the generator). */
  gain: number;
  /** Minimum ms between triggers of this cue — throttle + anti-overlap. */
  throttle: number;
  /** Higher wins: a lower-priority cue is muted while a higher one rings. */
  priority: number;
  /**
   * Max ± playback-rate jitter applied per trigger (0.06 = ±6%), so repeats
   * never sound like the same flat sample. Kept small/zero for the musical
   * one-shots so their pitch stays intentional.
   */
  pitch: number;
};

/**
 * Effective loudness ≈ MASTER_GAIN × gain, kept within the site's subtle
 * 15–35% band (the welcome sits a touch louder as a one-time moment).
 */
export const CUES: Record<CueName, CueSpec> = {
  tick: { url: tickUrl, gain: 0.14, throttle: 55, priority: 0, pitch: 0.08 },
  cardhover: { url: cardhoverUrl, gain: 0.16, throttle: 90, priority: 0, pitch: 0.05 },
  whoosh: { url: whooshUrl, gain: 0.18, throttle: 900, priority: 1, pitch: 0.05 },
  pop: { url: popUrl, gain: 0.3, throttle: 80, priority: 2, pitch: 0.06 },
  transition: { url: transitionUrl, gain: 0.18, throttle: 500, priority: 3, pitch: 0.03 },
  chime: { url: chimeUrl, gain: 0.3, throttle: 200, priority: 4, pitch: 0.03 },
  bloom: { url: bloomUrl, gain: 0.3, throttle: 400, priority: 5, pitch: 0.02 },
  startup: { url: startupUrl, gain: 0.42, throttle: 1000, priority: 6, pitch: 0 },
  // `drag` is a sustained loop managed separately, so it needs no throttle
  // and stays out of the one-shot priority ducking.
  drag: { url: dragUrl, gain: 0.15, throttle: 0, priority: 0, pitch: 0 },
};

/** The cue driven as a continuous loop rather than a one-shot. */
export const SUSTAIN_CUE: CueName = "drag";

export const MIX = {
  master: 0.85,
  /** Sustain fade envelope, in seconds. */
  sustainFadeIn: 0.12,
  sustainFadeOut: 0.22,
  /** Exponential-approach time constant for the sustain glide. */
  sustainGlide: 0.09,
  /** Clamp applied to a one-shot's intensity multiplier. */
  intensityFloor: 0.15,
  intensityCeiling: 1.3,
  /** How much intensity nudges playback rate on a one-shot. */
  intensityPitchBias: 0.06,
} as const;

/** Bounds for the sustain loop's level and playback rate. */
export const SUSTAIN_RANGE = {
  levelFloor: 0.7,
  levelCeiling: 1.5,
  rateFloor: 0.9,
  rateCeiling: 1.15,
  rateBase: 0.92,
  rateSpan: 0.16,
} as const;
